from utils import print_with_delay_horizontal, clear_terminal, space_align, space_align_without_deleted_text, dialogue_delay

# Story : Prolog

def Story_prolog(character_name):
    space_align(f'''Di sebuah pulau kecil bernama Pulau Everdawn, makhluk-makhluk hidup makmur. Semua kebutuhan mereka, mulai dari makanan, tempat tinggal, dan lainnya sangat terpenuhi. Penduduk pulau ini adalah ras monster yang telah hidup ratusan tahun dalam damai. Di antara mereka, ada seorang anak setengah harimau bernama {character_name}. Dia memiliki telinga layaknya seekor harimau, tetapi tubuhnya seperti manusia.''')
    space_align(f'''Sejak kecil, {character_name} sudah hidup sendiri karena tidak tahu siapa kedua orang tuanya. Dia hanya tahu bahwa dia memiliki satu anggota keluarga yang merupakan kakek angkatnya. Kakeknya mengasuh {character_name} sejak kecil, dan dia tahu bahwa kakeknya adalah satu-satunya keluarga yang tersisa. Kakeknya menemukan {character_name} di sebuah pantai dekat desa dan menamakannya {character_name} karena saat itu menjelang malam dan nama itu mirip dengan nama pulau tersebut''')
    space_align(f'''{character_name} telah berusia 15 tahun. Pada usia tersebut, di sana, dia sudah dianggap sebagai wanita dewasa sehingga dia tidak lagi tinggal bersama kakeknya. Meskipun sudah tidak tinggal bersama, {character_name} tetap sering berkunjung ke rumah kakeknya untuk sekedar menjenguk. {character_name} memiliki paras yang cantik, kulit putih mulus, dan banyak pemuda di desa terpana oleh kecantikannya.Dia baik hati, tidak pernah melakukan kejahatan, dan selalu menolong orang yang membutuhkan.''')
    space_align(f'Ketika Evelyn sedang bersama temannya di sebuah ladang tidak jauh dari desa, dia tidak sengaja mendengar percakapan beberapa pemuda-pemudi yang mengatakan ada hal janggal di tengah pulau. Rumor mengatakan bahwa ada penyihir yang mampu mengutuk orang yang mengunjungi tempatnya. Evelyn merasa biasa saja karena kakeknya sudah memberitahunya sejak dia berumur 7 tahun. Kakeknya berpesan agar Evelyn mengunjungi penyihir di tengah pulau jika dia sudah tidak ada. Saat itu, Evelyn tidak takut sama sekali dengan penyihir itu.')
    space_align(f'Dua tahun kemudian, ketika Evelyn berusia 17 tahun, mulai terjadi keanehan di sekitarnya. Awalnya, hanya prasangka, tetapi kemudian terjadi hal-hal aneh seperti hasil buruan yang semakin sedikit, beberapa pulau terkontaminasi zat aneh yang membuat orang tidak bisa minum, dan banyak lagi. Hingga prasangka yang paling menghantuinya terjadi, {character_name} bermimpi bahwa kakeknya akan terkena penyakit yang tidak bisa disembuhkan orang lain. Setelah mimpi itu, {character_name} langsung membereskan barang-barangnya dan menjenguk kakeknya yang tinggal di pinggir pantai. ')
    space_align(f'Ketika sampai, {character_name} terkejut mendapati kakeknya dalam keadaan sekarat. Kondisinya mengenaskan, kulit tubuhnya mengering, kesulitan bernapas, dan bahkan tidak bisa bangun dari tempat tidur. Kakeknya sadar bahwa ajalnya sudah dekat dan berharap Evelyn berada di sisinya. Sebelum menghembuskan nafas terakhir, dia memberikan sebuah surat kepada Evelyn untuk diberikan kepada penyihir yang pernah disebutnya. Setelah memberikan surat itu, kakeknya menghembuskan nafas terakhirnya.')
    space_align(f'{character_name} tidak tahu harus berbuat apa. Air mata mengalir, keringat bercucuran, dan rasanya ingin berteriak tapi tidak ada suara yang keluar. Hanya keheningan yang menyelimuti tempat itu. Dengan berat hati, Evelyn menguburkan kakeknya di dekat kediamannya sehingga ketika berkunjung, dia bisa bertemu kembali dengan kakeknya.')
    space_align(f'Satu minggu setelah kejadian tersebut, Pulau Everdawn semakin parah. Warga yang dulunya hidup damai sekarang saling melukai untuk bertahan hidup. Hanya beberapa orang yang masih waras, termasuk teman dekat {character_name} bernama Elen. {character_name} bertemu Elen ketika masih kecil. Saat itu, {character_name} takut berteman karena fisiknya yang seperti manusia membuatnya dijauhi anak-anak lain. Namun, Elen dengan senang hati mau berteman dengan {character_name}, dan mereka berteman hingga sekarang.')
    space_align(f'Setelah dari rumah kakeknya, {character_name} ingin berkunjung ke rumah Elen untuk menentukan apa yang harus dilakukan selanjutnya. Dibutuhkan satu minggu untuk sampai ke rumah Elen. Ketika tiba, Elen menyambutnya dengan baik dan menjamu dengan bahan seadanya. {character_name} tidak langsung mengungkapkan maksud dan tujuannya, tetapi berbasa-basi dahulu karena mereka hampir tidak bertemu lebih dari satu tahun setelah kejadian aneh di pulau ini.')
    dialogue_delay(f'Elen : "Surat apa itu?')
    dialogue_delay(f'{character_name}: Saya tidak tahu surat apa ini, tetapi kakek saya berpesan untuk memberikan surat ini kepada penyihir dan dengan itu kamu akan tahu mengapa semua ini terjadi di pulau ini')
    space_align(f'Walaupun sudah dijelaskan, Elen tetap khawatir. Namun, pada akhirnya, Elen memutuskan untuk ikut bersama {character_name} untuk bertemu penyihir karena dia juga sudah kehilangan orang-orang yang dicintainya. Hanya {character_name} yang masih menjadi temannya. Walaupun takut, mereka ingin mengungkap apa yang sebenarnya terjadi di Pulau Everdawn.')



# Story Line Act 1 Pencarian penyihir
def story_Act_1(character_name):
    space_align(f'Setelah mempersiapkan berbagai kebutuhan untuk menjelajah seperti makanan, tenda, dan juga peralatan untuk bertahan hidup, mereka berangkat dini hari. Hal ini karena perjalanan akan memakan waktu yang lumayan lama. Sebelum berangkat, {character_name} menanyakan kondisi Elen yang tampaknya tidak terlalu sehat karena kondisi tempat tinggal Elen yang berantakan dan adanya ketegangan antar masyarakat di sana. {character_name} berkata')
    dialogue_delay(f'{character_name}Apakah kamu baik-baik saja, Elen?')
    dialogue_delay(f'Elen pun mengangguk dan berkata')
    dialogue_delay(f'Elen : Iya, saya baik-baik saja, {character_name}, tidak perlu khawatir')
    space_align_without_deleted_text(f'Setelah itu, memastikan semua kondisi selesai, mereka berangkat untuk melakukan pencarian menemukan penyihir.')
